# T-Pot (Industrial)
# For docker-compose ...
version: '2.2'

networks:
  conpot_local:
  emobility_local:
  ewsposter_local:
  spiderfoot_local:
  ui-for-docker_local:

services:

# Conpot service
  conpot:
    container_name: conpot
    restart: always
    networks:
     - conpot_local
    ports:
     - "1025:1025"
     - "50100:50100"
    image: "dtagdevsec/conpot:1710"
    volumes:
     - /data/conpot/log:/var/log/conpot

# ELK services
## Logstash service
  logstash:
    container_name: logstash
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    image: "dtagdevsec/logstash:1710"
    volumes:
     - /data:/data
     - /var/log:/data/host/log

# Emobility service
  emobility:
    container_name: emobility
    restart: always
    networks:
     - emobility_local
    cap_add:
     - NET_ADMIN
    ports:
     - "8080:8080"
    image: "dtagdevsec/emobility:1710"
    volumes:
     - /data/emobility:/data/eMobility
     - /data/ews:/data/ews

# Ewsposter service
  ewsposter:
    container_name: ewsposter
    restart: always
    networks:
     - ewsposter_local
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    image: "dtagdevsec/ewsposter:1710"
    volumes:
     - /data:/data
     - /data/ews/conf/ews.ip:/opt/ewsposter/ews.ip

# Ui-for-docker service
  ui-for-docker:
    container_name: ui-for-docker
    command:  -H unix:///var/run/docker.sock --no-auth
    restart: always
    networks:
     - ui-for-docker_local
    ports:
     - "127.0.0.1:64299:9000"
    image: "dtagdevsec/ui-for-docker:1710"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

# Suricata service
  suricata:
    container_name: suricata
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    image: "dtagdevsec/suricata:1710"
    volumes:
     - /data/suricata/log:/var/log/suricata

# P0f service
  p0f:
    container_name: p0f
    restart: always
    network_mode: "host"
    image: "dtagdevsec/p0f:1710"
    volumes:
     - /data/p0f/log:/var/log/p0f
